import React from 'react';
import { useNavigate } from 'react-router-dom';

const ChatGPTQualityAnalysis = () => {
  const navigate = useNavigate();

  const goBack = () => {
    navigate('/thought-leadership');
  };

  return (
    <div style={styles.container}>
      {/* Back Button at Top */}
      <button onClick={goBack} style={styles.backButtonTop}>
        &larr; Back
      </button>

      {/* Article Header */}
      <header style={styles.header}>
        <h1 style={styles.title}>Quality and Recognizability of ChatGPT Responses in Comparison to Human-Authored Scholarship</h1>
        <p style={styles.subtitle}>Zachary Robers</p>
        <img 
          src="/images/article-images/chat.jpg" 
          alt="Placeholder for article image" 
          style={styles.heroImage} 
        />
      </header>

      {/* Article Body */}
      <article style={styles.article}>
        {/* Introduction Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Introduction</h2>
          <p>
            ChatGPT, a generative AI software created by OpenAI, is disrupting classrooms across the United States.
            The software, which uses a transformer neural network to generate responses to various prompts and questions,
            is being utilized by students to write essays and complete assignments...
          </p>
        </section>

        {/* Data Collection Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Data Collection</h2>
          <p>
            The intended population for inference in this study is all high school teachers in the United States.
            The teachers at East Chapel Hill High School, a public high school in Chapel Hill, North Carolina,
            are treated as a cluster sample and the teaching body at the school is assumed to be representative
            of the teaching body at any high school across the U.S...
          </p>
        </section>

        {/* Data Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Data</h2>
          <p>
            30 of the 90 teachers at East Chapel Hill High responded to one of the forms. Of the 30 respondents,
            21 correctly identified the response generated by ChatGPT, yielding a proportion of 0.7...
          </p>
        </section>

        {/* Statistical Methodology Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Statistical Methodology</h2>
          <p>
            Below is an outline of the necessary steps to construct a confidence interval for the proportion of
            teachers who can correctly identify which of two responses to an academic question was generated by ChatGPT...
          </p>
        </section>

        {/* Statistical Analysis Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Statistical Analysis</h2>
          <p>
            The confidence level for the proportion of teachers that can recognize the passage written by ChatGPT
            ranges from 0.53 to 0.87, meaning that the entire range is above 0.5...
          </p>
        </section>

        {/* Discussion Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Discussion on Error and Inconsistencies with a Classroom Environment</h2>
          <p>
            Ideally, a large random sample of high school teachers across the United States would be gathered to execute this study.
            However, generating such a sample is not at all practical...
          </p>
        </section>

        {/* Conclusion Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>Conclusion</h2>
          <p>
            This study uses confidence intervals and Fisher’s exact test to analyze the ability of high school teachers
            to detect the use of ChatGPT and high school teachers’ perception of the quality of ChatGPT responses...
          </p>
        </section>

        {/* References Section */}
        <section style={styles.section}>
          <h2 style={styles.sectionTitle}>References</h2>
          <ol style={styles.sourceList}>
            <li>OpenAI. "ChatGPT: AI Language Model." OpenAI, 2021.</li>
            <li>Gordon, Cindy. “How Are Educators Reacting to Chat GPT?” Forbes, 2023...</li>
            <li>Leigh, Dana. “How Does Chat GPT Actually Work?” TechRound, 2023...</li>
          </ol>
        </section>

        {/* Back Button at Bottom */}
        <button onClick={goBack} style={styles.backButtonBottom}>
          Thought Leadership Home
        </button>
      </article>
    </div>
  );
};

const styles = {
  container: {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: 'Arial, sans-serif',
    lineHeight: '1.6',
    color: '#333',
  },
  backButtonTop: {
    margin: '10px 0',
    padding: '10px 15px',
    fontSize: '1rem',
    color: '#2e4075',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    textAlign: 'left',
    textDecoration: 'underline',
  },
  backButtonBottom: {
    display: 'block',
    margin: '20px auto',
    padding: '10px 15px',
    fontSize: '1rem',
    color: '#2e4075',
    background: 'none',
    border: '1px solid #2e4075',
    borderRadius: '5px',
    cursor: 'pointer',
    textAlign: 'center',
  },
  header: {
    textAlign: 'center',
    marginBottom: '30px',
    color: '#2e4075',
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    margin: '10px 0',
  },
  subtitle: {
    fontSize: '1.2rem',
    color: '#555',
    marginBottom: '20px',
  },
  article: {
    marginTop: '20px',
  },
  section: {
    marginBottom: '30px',
  },
  sectionTitle: {
    fontSize: '1.8rem',
    fontWeight: 'bold',
    marginBottom: '10px',
    color: '#2e4075',
  },
  sourceList: {
    paddingLeft: '20px',
    fontSize: '1rem',
  },
  heroImage: {
    width: '100%',
    height: 'auto',
    borderRadius: '10px',
  },
};

export default ChatGPTQualityAnalysis;
